zzzz/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace zzzz.Models
{
    public class Image
    {
        [Key]
        [Display(Name = "ID")]
        public int ID { get; set; }
        [Display(Name = "Pic")]
        public string path { get; set; }
    }
}

zzzz/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using zzzz.Models;
using zzzz.Models.ORM;
using zzzz.Models.ORM.Repository_Interfaces;

namespace zzzz.Controllers
{
    public class ImageController : Controller
    {
        private IImageRep ImageRepository;
        private zzzz_DBFacade dbContext;

        public zzzz_DBFacade GetDBContext()
        {
            if (dbContext == null)
                dbContext = new zzzz_DBFacade();

            return dbContext;
        }

        public ImageController()
        {
            this.ImageRepository = RepositoryFactory.MakeImageRepository(GetDBContext());
        }

        //
        [Authorize(Users = "admin")]// GET: /Image/
        public ActionResult Index()
        {
            return View(ImageRepository.LoadAll().ToList());
        }
        [Authorize(Users = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Image model, HttpPostedFileBase file)
        {
            if (file!=null)
            {
                // code for saving the image file to a physical location.
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/dwn"), fileName);
                file.SaveAs(path);

                // prepare a relative path to be stored in the database and used to display later on.
                path = Url.Content(Path.Combine("~/Content/dwn", fileName));
                Image img = new Image();
                img.path = path;

                ImageRepository.Add(img);
                ImageRepository.Commit();

                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }
        [Authorize(Users = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image img = ImageRepository.Load(id);
            if (img == null)
            {
                return HttpNotFound();
            }
            return View(img);
        }

        // POST: /Script/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Image img = ImageRepository.Load(id);
            ImageRepository.Remove(img);
            ImageRepository.Commit();
            return RedirectToAction("Index");
        }
	}
}

zzzz/Views/Image/Create.cshtml
<!DOCTYPE html>
@section mainbar
{
    <div class="mainbar">
        @using (Html.BeginForm("Create", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" id="file" />
            <input type="submit" value="Create" class="btn btn-default" />
        }
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
 }

zzzz/Views/Image/Delete.cshtml
@model zzzz.Models.Image

@section mainbar
{<div class="mainbar">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Image</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.ID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ID)
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
}

zzzz/Views/Image/Index.cshtml
@model IEnumerable<zzzz.Models.Image>

<!DOCTYPE html>

@section mainbar
{<div class="mainbar">
        <p>
            @Html.ActionLink("Create New", "Create", "Image")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.path)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        <img width="100" height="100" src="@Url.Content(item.path)" />
                    </td>

                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }

        </table>
    </div>
}