zzzz/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc_test_0.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        [Authorize(Users = "admin")]
        public ActionResult Admin()
        {
            return View();
        }

    }
}

zzzz/Controllers/OrderController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using zzzz.Models;
using zzzz.Models.ORM;
using zzzz.Models.ORM.Repository_Interfaces;

namespace zzzz.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRep OrderRepository;
        private zzzz_DBFacade dbContext;

        public zzzz_DBFacade GetDBContext()
        {
            if (dbContext == null)
                dbContext = new zzzz_DBFacade();

            return dbContext;
        }

        public OrderController()
        {
            this.OrderRepository = RepositoryFactory.MakeOrderRepository(GetDBContext());
        }

        private Order ResolveScript(int id)
        {
            return ControllerUtils.ResolveObjectById(OrderRepository, id);
        }

        private OrderForView temp = new OrderForView();

        // GET: /Order/
        [Authorize(Users="admin")]
        public ActionResult Index()
        {
            return View(OrderRepository.LoadAll().ToList());
        }

        [Authorize(Users = "admin")]// GET: /Order/Details/5
        public ActionResult Details(int? id)
        {
            ICustomerRep CustomerRepository = RepositoryFactory.MakeCustomerRepository(GetDBContext());
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = OrderRepository.Load(id);
            Customer customer = CustomerRepository.Load(order.CustomerID);
            temp.Comment = order.Comment;
            temp.Cost = order.Cost;
            temp.Currentammount = order.Currentammount;
            temp.customer = customer;
            temp.CustomerID = order.CustomerID;
            temp.EventType = order.EventType;
            temp.OrderID = order.OrderID;
            temp.Regtime = order.Regtime;
            temp.ScriptID = order.ScriptID;
            temp.Status = order.Status;

            if (order == null)
            {
                return HttpNotFound();
            }
            return View(temp);
        }

        // GET: /Order/Create
        public ActionResult Create()
        {
            ICustomerRep CustomerRepository = RepositoryFactory.MakeCustomerRepository(GetDBContext());
            if (User.Identity.IsAuthenticated == false)
            {
                OrderForView order = new OrderForView();
                order.Regtime = DateTime.Now;
                temp = order;
                return View(order);
            }
            if (User.Identity.Name == "admin")
            {
                OrderForView order = new OrderForView();
                order.Regtime = DateTime.Now;
                temp = order;
                return View(order);
            }
            if (User.Identity.Name != "admin" && User.Identity.IsAuthenticated)
            {
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var user = manager.FindById(User.Identity.GetUserId());
                Customer customerInfo = CustomerRepository.Load(user.CustomerID);
                OrderForView order = new OrderForView();
                order.customer = customerInfo;
                order.Regtime = DateTime.Now;
                order.CustomerID = customerInfo.CustomerID;
                temp = order;
                return View(order);
            }
            return View();
        }

        // POST: /Order/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="OrderID,Comment,Cost,Currentammount,Status,Regtime,EventType,CustomerID,ScriptID")] Order order, OrderForView forview)
        {
            if (ModelState.IsValid)
            {
                ICustomerRep CustomerRepository = RepositoryFactory.MakeCustomerRepository(GetDBContext());
                if (User.Identity.Name == "admin")
                {
                    CustomerRepository.Add(forview.customer);
                    CustomerRepository.Commit();

                    order.CustomerID = forview.customer.CustomerID;
                    order.Status = "New";

                    OrderRepository.Add(order);
                    OrderRepository.Commit();
                    return RedirectToAction("Index");
                }
                if (!User.Identity.IsAuthenticated)
                {
                    CustomerRepository.Add(forview.customer);
                    CustomerRepository.Commit();

                    order.CustomerID = forview.customer.CustomerID;
                    order.Status = "New";

                    OrderRepository.Add(order);
                    OrderRepository.Commit();
                    return RedirectToAction("Thanks", "Home");
                }
                if (User.Identity.Name != "admin" && User.Identity.IsAuthenticated)
                {
                    var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                    var user = manager.FindById(User.Identity.GetUserId());
                    order.CustomerID = user.CustomerID;
                    order.Status = "New";

                    OrderRepository.Add(order);
                    OrderRepository.Commit();
                    return RedirectToAction("Thanks", "Home");
                }

            }

            return View(order);
        }

        [Authorize(Users = "admin")]// GET: /Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = OrderRepository.Load(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: /Order/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="OrderID,Comment,Cost,Currentammount,Status,Regtime,EventType,CustomerID,ScriptID")] Order order)
        {
            if (ModelState.IsValid)
            {
                Order ord = ResolveScript(order.OrderID);
                    ord.Comment = order.Comment;
                    ord.Cost = order.Cost;
                    ord.Currentammount = order.Currentammount;
                    ord.CustomerID = order.CustomerID;
                    ord.EventType = order.EventType;
                    ord.ScriptID = order.ScriptID;
                    ord.Status = order.Status;
                    OrderRepository.Commit();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        [Authorize(Users = "admin")]// GET: /Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = OrderRepository.Load(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: /Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = OrderRepository.Load(id);
            OrderRepository.Remove(order);
            OrderRepository.Commit();
            return RedirectToAction("Index");
        }

    }
}

zzzz/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>WhatWillDo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.3.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/cufon-yui.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/arial.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/cuf_run.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/radius.js")" type="text/javascript"></script>
</head>
<body>
    <div class="main">
        <div class="header">
            <div class="header_resize">
                <div class="menu_nav">
                    <ul>
                        <li class="active">@Html.ActionLink("Домашняя", "Index", "Home")</li>
                        <li>@Html.ActionLink("Посмотреть мероприятия", "ViewEvents", "Home")</li>
                        <li>@Html.ActionLink("Заказать мероприятие", "Create", "Order")</li>
                        <li>@Html.ActionLink("O нас", "AboutUs", "Home")</li>
                        @if(User.Identity.IsAuthenticated && User.Identity.Name!="admin")
                        {
                            <li>@Html.ActionLink("Кабинет", "ManageAccount", "Account")</li>
                        }
                        @if (User.Identity.Name == "admin")
                        {
                            <li>@Html.ActionLink("Для Админа", "Admin", "Admin")</li>
                        }
                    </ul>
                </div>
                <div class="clr"></div>
                <div class="logo">
                    <h1>what<span>willDo</span><small>планирование мероприятий</small></h1>
                </div>
                <div class="clr"></div>
            </div>
        </div>
        <div class="content">
            <div class="content_resize">
                @RenderSection("mainbar")
                @if (IsSectionDefined("sb"))
                {
                    @RenderSection("sb");
                }

                <div class="sidebar">
                    <div class="gadget">
                        <h3 class="star"><span>Пользователь:</span></h3>
                        <section id="login">
                            @Html.Partial("_LoginPartial")
                        </section>
                        <h3 class="star"><span>Дополнительная</span> навигация</h3>
                        <div class="clr"></div>
                        @if (IsSectionDefined("sb_menu"))
                        {
                            @RenderSection("sb_menu");
                        }
                        else
                        {
                            <ul class="sb_menu">
                                <li>@Html.ActionLink("Домашняя", "Index", "Home")</li>
                                <li>@Html.ActionLink("Посмотреть мероприятия", "ViewEvents", "Home")</li>
                                <li>@Html.ActionLink("Заказать мероприятие", "Create", "Order")</li>
                                <li>@Html.ActionLink("O нас", "AboutUs", "Home")</li>
                                @if (User.Identity.IsAuthenticated && User.Identity.Name != "admin")
                                {
                                    <li>@Html.ActionLink("Кабинет", "ManageAccount", "Account")</li>
                                }
                                @if(User.Identity.Name == "admin")
                                {
                                    <li>@Html.ActionLink("Для Админа", "Admin", "Admin")</li>
                                }
                            </ul>
                        }
                    </div>
                </div>
                <div class="clr"></div>
            </div>
        </div>
        <div class="fbg">
            <div class="fbg_resize">
                <div class="col c1">
                    <h2><span>  Istagram: Последнее</span></h2>
                    <a href="#"><img src="Content/images/pix1.jpg" width="240" height="240" alt="" /></a>
                </div>
                <div class="col c2">
                    <h2><span>Последний отзыв:</span></h2>
                    <p>
                        10/10<br />
                        <span>Стильно, модно, быстро!</span>
                    </p>
                </div>
                <div class="col c3">
                    <h2><span>Контакты</span></h2>
                    <p>Ниже предоставлена некоторая контактная информация</p>
                    <p>@Html.ActionLink("support@whatwilldo.com", "OrderEvent", "OrderEvent")</p>
                    <p>
                        +1 (123) 444-5677<br />
                        +1 (123) 444-5678
                    </p>
                    <p>Адрес: Харьков ул. Пушкина д. Колотушкина    </p>
                </div>
                <div class="clr"></div>
            </div>
        </div>
        <div class="footer">
            <div class="footer_resize">
                <p class="lf">Copyright &copy; <a href="#">Domain Name</a>. All Rights Reserved</p>
                <div class="clr"></div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>